import { Nunito } from 'next/font/google'

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const font = Nunito({ 
  subsets: ['latin'], 
});

export const metadata: Metadata = {
  title: 'Beker Buttons',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="pb-20 pt-28">
          {children}
        </div>
      </body>
    </html>
  )
}
